name: Service Container Example (Jobs on Container)
on: workflow_dispatch
jobs:
  XXXXXXXXXX:
    runs-on: ubuntu-latest
    container: node:16-bullseye

    services:
      nginx-srv:
        image: nginx:1.21.0

    steps:
      - shell: bash
        run: |
          curl http://nginx-srv
